### ISSUE TITLE
Using other canvas drawing libraries like D3 or P5.js

### ISSUE THREAD

**Issue by ff6347** [automat/sketch-context2d#5]
Just a quick question. Is it possible to use other JS libraries that draw to the canvas with your tool?

**Comment by automat** [comment]
Thats one of my main goals ;) I´m currently aiming for `paper.js`, guess `p5.js` is out of the question as there are too many dom-specific dependencies, but will look into other js processing impl. Also looking into `d3`. Everything not render-specific should work already as long as its accessible as an npm module.

**Comment by ff6347** [comment]
Cool. Looking forward to this and will give d3 a spin.
